# Site wide configuration

title:    Barbara Tozier Photographer
locale:   en_US
url:      http://barbaratozier.com


# Jekyll configuration adding something

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - bootstrap
  - autoprefixer-rails
# incremental: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  # parse_block_html: true

# Site owner
owner:
  name: Barbara Tozier
  avatar: website/tozier-avatar.jpg
  bio: "I'm a a conceptual artist whose medium is photography in all of its forms."
  email: info@barbaratozier.com
  twitter: logista
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: logista
  tumblr: logista


include: [".htaccess", "_pages"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "notes to myself.txt", "posting-guide.md"]

links:
  - title: Writing
    url: /writing/

defaults:
  -
    scope:
      path: ""
    values:
      share: false
